---
- name: firewalld rule
  ansible.posix.firewalld:
    zone: "{{ firewalld_rules[item.key]['zone'] | default(omit) }}"
    state: "{{ firewalld_rules[item.key]['state'] }}"
    permanent: "{{ firewalld_rules[item.key]['permanent'] | default(omit) }}"
    port: "{{ firewalld_rules[item.key]['port'] | default(omit) }}"
    service: "{{ firewalld_rules[item.key]['service'] | default(omit) }}"
    rich_rule: "{{ firewalld_rules[item.key]['rich_rule'] | default(omit) }}"
    source: "{{ firewalld_rules[item.key]['source'] | default(omit) }}"
    interface: "{{ firewalld_rules[item.key]['interface'] | default(omit) }}"
    masquerade: "{{ firewalld_rules[item.key]['masquerade'] | default(omit) }}"
    target: "{{ firewalld_rules[item.key]['target'] | default(omit) }}"
    icmp_block: "{{ firewalld_rules[item.key]['icmp_block'] | default(omit) }}"
    icmp_block_inversion: "{{ firewalld_rules[item.key]['icmp_block_inversion'] | default(omit) }}"
  with_dict: "{{ firewalld_rules }}"
  notify: restart firewalld
  when: firewalld_rules[item.key]['enabled']