---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # FirewallD
      firewalld:
        enabled: true
        service:
          enabled: true
          state: "started"

      # FirewallD -> install
      firewalld_install:
        enabled: true
        packages: [firewalld]

      # FirewallD -> rules
      firewalld_rules:
        port_80:
          enabled: true
          zone: "public"
          state: "enabled"
          port: "80/tcp"
          permanent: true
          immediate: true
        service_http:
          enabled: true
          zone: "public"
          state: "enabled"
          service: "http"
          permanent: true
          immediate: true
        service_https:
          enabled: true
          zone: "public"
          state: "enabled"
          service: "https"
          permanent: true
          immediate: true
      # ...
  tasks:
    - name: role darexsu firewalld
      include_role:
        name: darexsu.firewalld